name: apiverve_datamasking
description: Data Masking is a powerful tool for detecting and masking sensitive information in text. It can identify and redact emails, phone numbers, SSNs, credit cards, IP addresses, URLs, and dates.
version: 1.1.14
homepage: https://apiverve.com/marketplace/datamasking?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/datamasking-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
